In [3]:
import numpy as np

# Load the employee dataset as a NumPy structured array.
employees = np.genfromtxt(
    "employee_salary_dataset.csv",
    delimiter=",",
    names=True,
    dtype=None,
    encoding="utf-8",
)

employees[:5]

array([(1, 'Employee_1', 'Marketing', 15, 'Master', 53, 'Female', 'Delhi', 111416),
       (2, 'Employee_2', 'Operations',  7, 'Bachelor', 25, 'Female', 'Bangalore',  95271),
       (3, 'Employee_3', 'IT', 12, 'High School', 51, 'Female', 'Hyderabad',  69064),
       (4, 'Employee_4', 'Operations',  8, 'PhD', 44, 'Male', 'Delhi',  95091),
       (5, 'Employee_5', 'Operations', 15, 'Master', 36, 'Female', 'Delhi', 132450)],
      dtype=[('EmployeeID', '<i8'), ('Name', '<U11'), ('Department', '<U10'), ('Experience_Years', '<i8'), ('Education_Level', '<U11'), ('Age', '<i8'), ('Gender', '<U6'), ('City', '<U9'), ('Monthly_Salary', '<i8')])

# NumPy Arrays for Employee Salary EDA

This practical uses only NumPy arrays and array operations to study employee demographics, experience, roles, education, cities, and monthly salary.

In [4]:
# Structured-array fields and numeric columns used throughout the analysis.
print("records:", employees.shape[0])
print("fields:", employees.dtype.names)

experience = employees["Experience_Years"]
age = employees["Age"]
salary = employees["Monthly_Salary"]
print("experience sample:", experience[:5])
print("salary sample:", salary[:5])

records: 50
fields: ('EmployeeID', 'Name', 'Department', 'Experience_Years', 'Education_Level', 'Age', 'Gender', 'City', 'Monthly_Salary')
experience sample: [15  7 12  8 15]
salary sample: [111416  95271  69064  95091 132450]


## 1. Arrays vs Python Lists
NumPy stores homogeneous values compactly and applies compiled operations to whole arrays. Python lists store references to Python objects, so NumPy arrays generally use less memory and run faster for numeric workloads.
## 2. Array Creation
Create arrays with the core constructors requested in the practical.


In [5]:
import timeit

list_values = list(range(1_000_000))
array_values = np.arange(1_000_000)
list_time = timeit.timeit("sum(value * 2 for value in list_values)", globals=globals(), number=3)
array_time = timeit.timeit("np.sum(array_values * 2)", globals=globals(), number=3)
print(f"Python list memory estimate: {sum(value.__sizeof__() for value in list_values) / 1024**2:.2f} MB")
print(f"NumPy array memory: {array_values.nbytes / 1024**2:.2f} MB")
print(f"list time: {list_time:.4f}s | NumPy time: {array_time:.4f}s")

Python list memory estimate: 26.70 MB
NumPy array memory: 7.63 MB
list time: 0.0879s | NumPy time: 0.0064s


In [6]:
zeros = np.zeros(5, dtype=int)
ones = np.ones(5, dtype=int)
sequence = np.arange(0, 20, 2)
percentile_grid = np.linspace(0, 100, 6)

print("zeros:", zeros)
print("ones:", ones)
print("arange:", sequence)
print("linspace:", percentile_grid)

zeros: [0 0 0 0 0]
ones: [1 1 1 1 1]
arange: [ 0  2  4  6  8 10 12 14 16 18]
linspace: [  0.  20.  40.  60.  80. 100.]


In [7]:
salary_array = np.asarray(salary)
print("shape:", salary_array.shape)
print("ndim:", salary_array.ndim)
print("dtype:", salary_array.dtype)
print("size:", salary_array.size)
print("itemsize:", salary_array.itemsize, "bytes")

print("first salary:", salary_array[0])
print("first five salaries:", salary_array[:5])
print("last five salaries:", salary_array[-5:])

shape: (50,)
ndim: 1
dtype: int64
size: 50
itemsize: 8 bytes
first salary: 111416
first five salaries: [111416  95271  69064  95091 132450]
last five salaries: [ 88208  58828  43711  28420 121752]


In [8]:
salary_matrix = salary_array[:20].reshape(4, 5)
salary_cube = salary_array[:24].reshape(2, 3, 4)

print("2D array:\n", salary_matrix)
print("2D row 1:", salary_matrix[1])
print("2D rows 1-2, columns 2-4:\n", salary_matrix[1:3, 2:5])
print("nD element [1, 2, 3]:", salary_cube[1, 2, 3])
print("nD first block:\n", salary_cube[0])

2D array:
 [[111416  95271  69064  95091 132450]
 [ 65818  70525  44830  42429  31893]
 [141381 104909  72333  28436  99290]
 [101213  30895  44738  55746  74377]]
2D row 1: [65818 70525 44830 42429 31893]
2D rows 1-2, columns 2-4:
 [[44830 42429 31893]
 [72333 28436 99290]]
nD element [1, 2, 3]: 64790
nD first block:
 [[111416  95271  69064  95091]
 [132450  65818  70525  44830]
 [ 42429  31893 141381 104909]]


In [9]:
# Element-wise operations and vectorization avoid explicit row-by-row loops.
annual_salary = salary_array * 12
salary_after_raise = salary_array * 1.08
experience_bonus = experience * 2_000
adjusted_salary = salary_array + experience_bonus

print("annual salary sample:", annual_salary[:5])
print("8% raise sample:", salary_after_raise[:5])
print("experience bonus sample:", experience_bonus[:5])
print("adjusted salary sample:", adjusted_salary[:5])

annual salary sample: [1336992 1143252  828768 1141092 1589400]
8% raise sample: [120329.28 102892.68  74589.12 102698.28 143046.  ]
experience bonus sample: [30000 14000 24000 16000 30000]
adjusted salary sample: [141416 109271  93064 111091 162450]


In [10]:
# Broadcasting: add one department-level allowance to every employee in that department.
department_names = np.unique(employees["Department"])
department_allowances = np.arange(department_names.size) * 1_000
allowance_by_employee = department_allowances[
    np.searchsorted(department_names, employees["Department"])
]

salary_with_allowance = salary_array + allowance_by_employee
print("departments:", department_names)
print("allowances:", department_allowances)
print("broadcasted allowances:", allowance_by_employee[:10])
print("salary with allowance:", salary_with_allowance[:10])

departments: ['Finance' 'HR' 'IT' 'Marketing' 'Operations']
allowances: [   0 1000 2000 3000 4000]
broadcasted allowances: [3000 4000 2000 4000 4000    0 2000 2000 2000 4000]
salary with allowance: [114416  99271  71064  99091 136450  65818  72525  46830  44429  35893]


In [11]:
# Aggregation functions summarize the whole employee population.
print("salary sum:", np.sum(salary_array))
print("salary mean:", np.mean(salary_array))
print("salary minimum:", np.min(salary_array))
print("salary maximum:", np.max(salary_array))
print("salary standard deviation:", np.std(salary_array))
print("salary variance:", np.var(salary_array))

# Row-wise and column-wise summaries on a 2D salary matrix.
print("row sums:", np.sum(salary_matrix, axis=1))
print("column means:", np.mean(salary_matrix, axis=0))
print("row minimums:", np.min(salary_matrix, axis=1))
print("column maximums:", np.max(salary_matrix, axis=0))

salary sum: 4114440
salary mean: 82288.8
salary minimum: 28420
salary maximum: 149123
salary standard deviation: 33184.53047550922
salary variance: 1101213062.88
row sums: [503292 255495 446349 306969]
column means: [104957.    75400.    57741.25  55425.5   84502.5 ]
row minimums: [69064 31893 28436 30895]
column maximums: [141381 104909  72333  95091 132450]


In [12]:
# Boolean indexing selects employees matching a condition.
high_salary = salary_array >= 100_000
experienced = experience >= 10
print("high-salary employees:", employees[high_salary][["Name", "Monthly_Salary"]])
print("experienced employees:", employees[experienced][["Name", "Experience_Years"]])
print("experienced high earners:", np.sum(experienced & high_salary))

# Fancy indexing selects chosen positions without a loop.
selected_positions = np.array([0, 4, 9, 14])
print("selected names:", employees["Name"][selected_positions])
print("selected salaries:", salary_array[selected_positions])

high-salary employees: [('Employee_1', 111416) ('Employee_5', 132450) ('Employee_11', 141381)
 ('Employee_12', 104909) ('Employee_16', 101213) ('Employee_23', 122888)
 ('Employee_25', 132455) ('Employee_27', 119660) ('Employee_28', 118179)
 ('Employee_33', 127946) ('Employee_34', 134616) ('Employee_35', 130983)
 ('Employee_38', 149123) ('Employee_41', 107989) ('Employee_50', 121752)]
experienced employees: [('Employee_1', 15) ('Employee_3', 12) ('Employee_5', 15)
 ('Employee_7', 14) ('Employee_8', 17) ('Employee_10', 18)
 ('Employee_15', 10) ('Employee_17', 18) ('Employee_18', 12)
 ('Employee_20', 10) ('Employee_22', 14) ('Employee_23', 16)
 ('Employee_24', 15) ('Employee_26', 14) ('Employee_28', 16)
 ('Employee_29', 13) ('Employee_30', 18) ('Employee_31', 15)
 ('Employee_32', 13) ('Employee_34', 15) ('Employee_35', 13)
 ('Employee_40', 12) ('Employee_42', 11) ('Employee_43', 19)
 ('Employee_44', 17) ('Employee_50', 10)]
experienced high earners: 7
selected names: ['Employee_1' 'Employ

In [13]:
# Random numbers with a fixed seed make simulations reproducible.
rng = np.random.default_rng(42)
performance_scores = rng.normal(loc=75, scale=8, size=employees.size)
performance_scores = np.clip(performance_scores, 0, 100)

simulation = rng.integers(0, 2, size=(employees.size, 3))
print("performance scores:", performance_scores[:10].round(2))
print("three simulation trials for first five employees:\n", simulation[:5])

# Re-seeding reproduces the same random sequence.
rng_again = np.random.default_rng(42)
print("same first score after reseeding:", rng_again.normal(75, 8))

performance scores: [77.44 66.68 81.   82.52 59.39 64.58 76.02 72.47 74.87 68.18]
three simulation trials for first five employees:
 [[1 1 1]
 [1 0 1]
 [0 1 1]
 [0 1 1]
 [0 0 0]]
same first score after reseeding: 77.43773663803545


## NumPy EDA Takeaways

- Use `shape`, `ndim`, `dtype`, `size`, and `itemsize` to understand an array.
- Use vectorized arithmetic, broadcasting, boolean indexing, and fancy indexing for concise employee analysis.
- Use axis `0` for column-wise summaries and axis `1` for row-wise summaries in a 2D array.
- Seed random generators when simulation results need to be reproduced.